WebApplication/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BLL.Interface.Services;

namespace WebApplication.Controllers
{
    public class IndexController : Controller
    {
        private readonly ISiteDescriptionService _descriptionService;
        private readonly IUserService _userService;

        public IndexController(ISiteDescriptionService sdService, IUserService uService)
        {
            _descriptionService = sdService;
            _userService = uService;
        }
        
        [HttpGet]
        public JsonResult GetDescription()
        {
            var siteDescription = _descriptionService.GetDescriptionEntity(1);

            return Json(siteDescription.Text, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetRole()
        {
            string email = Membership.GetUser().UserName;
            var roleId = _userService.GetUserByEmail(email).RoleId;
           
            return Json(roleId, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public void SetText(string text)
        {
           _descriptionService.ChangeText(1, text);
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="albumsApp">
<head>
    <base href="/" />
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular")
    @*<script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-route.min.js"></script>
    <script src="~/Scripts/AngularScripts/module.js"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Photo gallery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @Html.Partial("_MenuPartial")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_MenuPartial.cshtml
@if (Request.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <ul class="nav navbar-nav navbar-left" style="margin-left: 7%">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                    Albums
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/Angular/ViewAll">View all albums</a></li>
                    <li><a href="/Angular/AddAlbum">Add new album</a></li>
                    <li><a href="/Angular/AddImage">Add new image</a></li>
                </ul>
            </li>
        </ul>
    </nav>
}